--- Test 2 output ---

vector.insert(5, 1) ``threw an out_of_range exception;exception-thrown-1;15``
vector.insert(7, 0)
vector.insert(6, 0)
vector.insert(4, 2)
vector = ``6 7 4;vector-1;20``

vector.insert(12, 1)
vector.insert(1, 3)
vector = ``6 12 7 1 4;vector-2;20``

vector.insert(7, 0)
vector.insert(5, 0)
vector.insert(19, 7)
vector.insert(5, 9) ``threw an out_of_range exception;exception-thrown-2;15``
vector = ``5 7 6 12 7 1 4 19;vector-3;20``
