--- Test 4 output ---

vector.remove(0) ``threw an out_of_range exception;exception-thrown;15``
vector.push_back(19)
vector.push_back(1)
vector.push_back(7)
vector.push_back(12)
vector.push_back(2)
vector = ``19 1 7 12 2;vector-1;15``

vector.remove(0)
vector = ``1 7 12 2;vector-2;15``

vector.remove(3)
vector = ``1 7 12;vector-3;15``

vector.remove(1)
vector = ``1 12;vector-4;15``

vector.remove(0)
vector.remove(0)
``vector =;empty-vector;15``
